version: '3.7'
services:
  auto-m4b:
    #image: seanap/auto-m4b
    build: .
    container_name: auto-m4b
    volumes:
      - /srv/dev-disk-by-uuid-BAB67C98B67C573B/share2/docker/appdata/autom4b:/config
      - /srv/dev-disk-by-uuid-BAB67C98B67C573B/data/temp:/temp
    environment:
      - PUID=1000
      - PGID=1000
      - CPU_CORES=2
      - MAKE_BACKUP=N